package errors

import "errors"

var (
	ErrInvalidSignature           = errors.New("invalid signature")
	ErrInvalidRequestBody         = errors.New("invalid request body")
	ErrInvalidEventType           = errors.New("invalid event type")
	ErrValidationFailed           = errors.New("validation failed")
	ErrUserNotAuthenticated       = errors.New("user not authenticated")
	ErrOrganizationNotFound       = errors.New("organization not found")
	ErrUnexpectedSigningMethod    = errors.New("unexpected signing method")
	ErrInvalidToken               = errors.New("invalid token")
	ErrUserNotFound               = errors.New("user not found")
	ErrClerkUserNotFound          = errors.New("clerk user not found")
	ErrUserFailedToCreate         = errors.New("user failed to create")
	ErrUserBanned                 = errors.New("user banned")
	ErrMaxOrganizationsReached    = errors.New("max organizations reached")
	ErrInvalidOrganizationID      = errors.New("invalid organization UUID")
	ErrOrganizationFailedToCreate = errors.New("organization failed to create")
	ErrEndpointsNotFound          = errors.New("endpoints not found")
	ErrInvalidEndpointID          = errors.New("invalid endpoint UUID")
	ErrEndpointNotFound           = errors.New("endpoint not found")
	ErrEndpointFailedToUpdate     = errors.New("endpoint failed to update")
	ErrWorkflowsNotFound          = errors.New("workflows not found")
	ErrInvalidWorkflowID          = errors.New("invalid workflow UUID")
	ErrWorkflowNotFound           = errors.New("workflow not found")
	ErrWorkflowFailedToUpdate     = errors.New("workflow failed to update")
	ErrInvalidRequest             = errors.New("invalid request")
	ErrInvalidStepID              = errors.New("invalid step UUID")
	ErrInvalidConnexionID         = errors.New("invalid connexion UUID")
)
